// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpfOj6OnF08VRRIhEBCcYeG7m-aNrhiik',
    appId: '1:20156473626:web:ccad3118bace573ea68ca3',
    messagingSenderId: '20156473626',
    projectId: 'halisahaapp',
    authDomain: 'halisahaapp.firebaseapp.com',
    storageBucket: 'halisahaapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFtPEMxEODIOEHDwENmOE9GvrshT2Sz4M',
    appId: '1:20156473626:android:dd402f472c7b26eea68ca3',
    messagingSenderId: '20156473626',
    projectId: 'halisahaapp',
    storageBucket: 'halisahaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAON7r4WEff5pijaVIcRNCB87YbfEQ-0ko',
    appId: '1:20156473626:ios:272e239f1db11696a68ca3',
    messagingSenderId: '20156473626',
    projectId: 'halisahaapp',
    storageBucket: 'halisahaapp.appspot.com',
    iosClientId: '20156473626-scubjf8jd43nu79rlvdj56522uuec3fk.apps.googleusercontent.com',
    iosBundleId: 'com.goldenmoon.app',
  );
}
